-- Exhaustive self-checking testbench for mult_shift_add (sequential).
--
-- Space: A_in in 0..255 x B_in in 0..255 = 65,536 products, R_out = A*B (16 bits).
--
-- Protocol characterized from the RTL (reset active low, asynchronous):
--   * the rising edge that samples start='1' in IDLE captures A_in/B_in (tick 1);
--   * 8 CALC edges follow; done='1' is visible after tick LATENCY = 9;
--   * done stays '1' while start='1' (WAIT_LOW), then falls one edge after start='0';
--   * R_out keeps the product after done falls (R_reg is not cleared in IDLE);
--   * R_out is NOT stable during CALC (the accumulator is exposed), so it is only
--     checked when done='1'.
-- Each product uses one of four start modes, selected by B mod 4:
--   pulse (start high for tick 1 only, as generated by ual_8), or start held
--   until done plus 0, 1 or 2 extra edges.
-- Operands are replaced by their complement after the capture edge when A is odd,
-- which checks that the multiplier works on the captured copy.

library ieee;
use ieee.std_logic_1164.all;
use work.tb_pkg.all;

entity tb_mult_shift_add is
end entity tb_mult_shift_add;

architecture sim of tb_mult_shift_add is
    constant HALF_PERIOD : time     := 5 ns;
    constant LATENCY     : positive := 9;
    constant TIMEOUT     : time     := 20 ms;

    signal clk     : std_logic := '0';
    signal running : boolean   := true;
    signal reset   : std_logic := '0';
    signal start   : std_logic := '0';
    signal a_in    : std_logic_vector(7 downto 0) := (others => '0');
    signal b_in    : std_logic_vector(7 downto 0) := (others => '0');
    signal r_out   : std_logic_vector(15 downto 0);
    signal done    : std_logic;
begin

    clk <= not clk after HALF_PERIOD when running else '0';

    dut : entity work.mult_shift_add
        port map (clk => clk, reset => reset, start => start,
                  A_in => a_in, B_in => b_in, R_out => r_out, done => done);

    watchdog : process
    begin
        wait until not running for TIMEOUT;
        assert not running report "TB_TIMEOUT tb_mult_shift_add" severity failure;
        wait;
    end process watchdog;

    stim : process
        constant EXPECTED_VECTORS : natural := 256 * 256;
        variable vectors  : natural := 0;
        variable directed : natural := 0;
        variable errors   : natural := 0;

        -- Advance one rising edge; inputs are driven and outputs sampled on falling edges
        procedure tick is
        begin
            wait until rising_edge(clk);
            wait until falling_edge(clk);
        end procedure;

        procedure run_mul(ia, ib : natural; mode : integer; scramble : boolean) is
            constant EXP : std_logic_vector(15 downto 0) := to_slv(ia * ib, 16);
            constant CTX : string := " A=" & hex(ia, 2) & " B=" & hex(ib, 2);
        begin
            a_in  <= to_slv(ia, 8);
            b_in  <= to_slv(ib, 8);
            start <= '1';
            for e in 1 to LATENCY loop
                tick;
                if e = 1 then
                    if mode < 0 then
                        start <= '0';
                    end if;
                    if scramble then
                        a_in <= to_slv(255 - ia, 8);
                        b_in <= to_slv(255 - ib, 8);
                    end if;
                end if;
                if e < LATENCY and done /= '0' then
                    report "FATAL: done asserted early at tick " & integer'image(e) & CTX severity failure;
                elsif e = LATENCY and done /= '1' then
                    report "FATAL: done not asserted at tick " & integer'image(LATENCY) & CTX severity failure;
                end if;
            end loop;
            if r_out /= EXP then
                tb_error(errors, "product" & CTX & " got " & hex(r_out) & " exp " & hex(EXP));
            end if;
            if mode >= 0 then
                for h in 1 to mode loop
                    tick;
                    if done /= '1' or r_out /= EXP then
                        tb_error(errors, "held start: done/R_out not stable" & CTX);
                    end if;
                end loop;
                start <= '0';
            end if;
            tick;
            if done /= '0' or r_out /= EXP then
                tb_error(errors, "after release: expected done=0 and R_out kept" & CTX);
            end if;
        end procedure;

    begin
        -- D1: reset held low with start='1' and non-zero operands: nothing is captured
        start <= '1';
        a_in  <= x"FF";
        b_in  <= x"FF";
        for i in 1 to 4 loop
            tick;
            directed := directed + 1;
            if done /= '0' or r_out /= x"0000" then
                tb_error(errors, "reset: outputs not cleared at tick " & integer'image(i));
            end if;
        end loop;
        start <= '0';
        reset <= '1';
        tick;

        -- Exhaustive products
        for ia in 0 to 255 loop
            for ib in 0 to 255 loop
                run_mul(ia, ib, (ib mod 4) - 1, ia mod 2 = 1);
                vectors := vectors + 1;
            end loop;
        end loop;

        -- D2: asynchronous reset in the middle of CALC clears done and R_out immediately
        a_in  <= x"FF";
        b_in  <= x"FF";
        start <= '1';
        for i in 1 to 4 loop
            tick;
        end loop;
        wait for 2 ns;
        reset <= '0';
        wait for 1 ns;
        directed := directed + 1;
        if done /= '0' or r_out /= x"0000" then
            tb_error(errors, "async reset during CALC did not clear outputs");
        end if;
        start <= '0';
        wait until falling_edge(clk);
        tick;
        reset <= '1';
        tick;

        -- D3: recovery after reset, both start modes
        run_mul(200, 3, 0, false);
        run_mul(255, 255, -1, false);
        directed := directed + 2;

        running <= false;
        tb_summary("tb_mult_shift_add", vectors, EXPECTED_VECTORS, directed, errors);
        wait;
    end process stim;

end architecture sim;
